language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- TRAVIS_TAG="Build-2019.4.9f1" PROJECT_NAME="SailingWithTheGods" UNITY_PROJECT_PATH="."


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- chmod a+x ./travis-build/*.sh

install:
- ./travis-build/install-unity.sh

script:
- ./travis-build/build.sh
