language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- TRAVIS_TAG="Build-2019.4.9f1" PROJECT_NAME="SailingWithTheGods" UNITY_PROJECT_PATH="."


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

git:
  submodules: false
  
# https://stackoverflow.com/questions/48346696/travis-ci-loading-private-submodule
before_install:
- chmod a+x ./travis-build/*.sh
- sed -i 's/git@github.com:/https:\/\/$GIT_USER:$GIT_TOKEN@github.com\//' .gitmodules
- git submodule update --init --recursive

install:
- ./travis-build/install-unity.sh

script:
- ./travis-build/build.sh
